### ISSUE TITLE
Option to preserve data frame row ordering for factor levels

### ISSUE THREAD

**Issue by jhelvy** [TidierOrg/TidierPlots.jl#12] opened 2023-05-10 13:43 UTC
Hi! I'm not a Julia user (yet) but I'm thrilled to see this being brought to Julia! Since things are still relatively fresh, I wanted to try to inject some ideas to potentially shape how the package is being built. 

One thing that drives me bonkers about R's {ggplot2} is factor ordering. Something _very_ simple like trying to sort a bar chart can still be annoyingly unintuitive (especially to beginners). Here's an example:

```r
library(tidyverse)

mpg %>% 
  count(manufacturer) %>% 
  ggplot() + 
  geom_col(aes(x = n, y = manufacturer))
``` 

This produces an unsorted bar chart:

![unsorted-bars](https://github.com/TidierOrg/TidierPlots.jl/assets/9012994/8cdc7a45-5c9d-49a9-8f8c-4b38f1979278)

If you wanted to sort the manufacturers based on `n`, many people make the mistake of sorting the _data frame_ and assuming the reordered rows will pass through to the bars, like this:

```r
mpg %>% 
  count(manufacturer) %>% 
  arrange(n) %>% 
  ggplot() + 
  geom_col(aes(x = n, y = manufacturer))
```

But this produces the same chart! 🤦

To actually get a sorted bar chart, you have to reorder the _factors_. There are many ways to do it - here's what I typically do:

```r
mpg %>% 
  count(manufacturer) %>% 
  ggplot() + 
  geom_col(aes(x = n, y = reorder(manufacturer, n)))
``` 

I find this rather unintuitive though because the ordering of the rows in the data frame won't match the factor ordering (which is rather opaque to the user). 

It seems like there could be a relatively easy fix though to add an argument somewhere that just says "preserve the factor ordering based on the data frame row order". It's such a simple idea and it would be a really, really nice fix to something that is rather difficult to try to fix now in R's ggplot without probably breaking a ton of dependencies. 

One thought is to implement it somewhere in the `ggplot()` call itself, something like `ggplot(freeze_factors = TRUE)`, such that the factor ordering in any following geom will take that of the data frame order. This is obviously R code, but hopefully my intent is clear. I don't really know where something like this could be brought in for Julia, but it's still early enough on that I wanted to voice this idea before too much else gets baked in. 

Another idea is to introduce another function that modifies the factor levels of all factor / character variables to match that of the row ordering. In R, I've been experimenting with a function I'm calling `lock_factors()` that does just that. The use case would work like this:

```r
mpg %>% 
  count(manufacturer) %>% 
  arrange(n) %>% 
  lock_factors() %>% 
  ggplot() + 
  geom_col(aes(x = n, y = manufacturer))
```

So it's just an intermediate step that should fix the issue. And of course you could potentially specify the specific variables you want to "lock", e.g. `lock_factors(manufacturer)`, etc. 

Anyway, just wanted to throw this thought out here. One day if I ever start using Julia maybe I can contribute to this wonderful effort you all are doing!

**Comment by jhelvy** [comment] 2023-05-10 16:10
FYI, I just pushed an R package that uses the `lock_factors()` idea: https://github.com/jhelvy/factorlock

I whipped that together very, very quickly, so it's not at all tested. But it does appear to be working as expected, and surprisingly solves the issue I've raised here quite well. But that's R. It's something that I think should definitely be considered in Julia since you get the benefit of building from a new starting point.

**Comment by rdboyes** [comment] 2023-05-10 17:03
Thanks for this suggestion! I completely agree - factors cause probably 80% of my problems with ggplot (and R in general). There are some helper functions in AoG for handling non-numeric variables that might help implement something like what you’re taking about. 

I do want to be really careful about deviating from ggplot’s behaviour in general, ideally having it behave like ggplot unless an option is toggled to enable “better” behaviour. For most users I imagine “predictable” beats “improved” in most cases. 

I’ll have to look into how best to implement this - any ideas welcome!

**Comment by kdpsingh** [comment] 2023-05-10 18:26
Thanks @jhelvy! Julia supports categorical variables (CategoricalArrays.jl) that are essentially R's equivalent of factors.

The plan in Tidier.jl (and eventually moving to TidierData.jl) is to support functions similar to the {forcats} R package.

It's on our roadmap here: https://github.com/TidierOrg/Tidier.jl/issues/81

Once we integrate this in Tidier.jl, we should be able to match R's factor ordering behavior a bit more closely in TidierPlots.jl.

**Comment by kdpsingh** [comment] 2023-05-10 18:34
Agreeing with @rdboyes, the package's main philosophy is to mimic tidyverse/ggplot2 to serve as a bridge for R users to move some of their workflow to Julia.

We may at some point diverge to enable new use cases (using multiple dispatch), but I think we want to first faithfully replicate/implement before we make any big decisions around divergence.

The only place we diverge right now in Tidier.jl is in functions that refer to Julia-specific data types, eg `as_float()` instead of `as_numeric()`.

**Comment by kdpsingh** [comment] 2023-05-11 01:45
Question for @jhelvy: Would implementing the equivalent of `forcats::fct_inorder()` in Julia fix this issue for you?

See the docs for the R version of this here: https://forcats.tidyverse.org/reference/fct_inorder.html

**Comment by jhelvy** [comment] 2023-05-11 10:10
Well how about that - didn't know about `fct_inorder()`! Yes that for the most part works, e.g.:

```r
mpg %>% 
  count(manufacturer) %>% 
  arrange(n) %>% 
  mutate(manufacturer = fct_inorder(manufacturer)) %>% 
  ggplot() + 
  geom_col(aes(x = n, y = manufacturer))
```

This may be my new preferred approach since I always find sorting the rows with `arrange()` to be the most intuitive way to get the factors in the order I want. That said, it still requires considerable more knowledge and effort by the user to remember to insert `mutate(var = fct_inorder(var))`. 

This is similar to what I've come up with in my (hastily made) [{factorlock}](https://github.com/jhelvy/factorlock) package:

```r
remotes::install_github("jhelvy/factorlock")

mpg |>
  count(manufacturer) |>
  arrange(n) |>
  factorlock::lock_factors() |>
  ggplot() +
  geom_col(aes(x = n, y = manufacturer))
```

The only real difference is `factorlock::lock_factors()` "locks" the factor ordering for all categorical variables. It's less to remember (there are sooo many `fct_*()` functions), so you just use `arrange()` then "lock" everything. Not sure yet if it's a good idea or not but it works! 

I know the goal is (at least for now) to replicate existing ggplot implementations, so if there is a {forecats} equivalent then that should suffice. I'd argue that {forecats} is somewhat of a _necessary_ package to make ggplot useable for categorical data, otherwise the factor stuff will drive everyone mad. I never use {forecats} except for making plots.

**Comment by kdpsingh** [comment] 2023-08-20 23:05
We’ve now built out TidierCats.jl as a {forcats} implementation so we should revisit this issue to see if TidierPlots.jl works as intended.

**Comment by rdboyes** [comment] 2023-09-30 17:15
The way this currently works: 

```
x = @chain mtcars begin 
  @mutate(manufacturer = str_replace(Model, " .*", ""))
  @count(manufacturer)
  ggplot
    geom_col(@aes(x = manufacturer, y = n))
end
```

![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/7eb36c9d-c78b-4b0e-bbd8-1da94206bff3)

x = @chain mtcars begin 
  @mutate(manufacturer = str_replace(Model, " .*", ""))
  @mutate(manufacturer = cat_infreq(categorical(manufacturer)))
  @count(manufacturer)
  ggplot
    geom_col(@aes(x = manufacturer, y = n))
end

![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/8c5c06e1-3bd9-4f2b-abe5-b24e62547e17)

**Comment by jhelvy** [comment] 2023-09-30 18:11
Man, I think I actually like this syntax _better_ than in R. The ability to run code up to a point in the chain without have to remove the `%>%` or `+` is so nice! 

Unrelated to this issue, but in Julia if you had the ggplot object `x`, could you "add" more layers to it like in R? What's the equivalent of something like:

```r
x + theme_bw()
```

Would you have to make a new chain for that?

**Comment by rdboyes** [comment] 2023-09-30 19:06
Yes, this works already for both addition "modes", e.g.

```
plot = @chain mtcars begin
    ggplot
        geom_point(@aes(x = WT, y = MPG))
end
```
![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/3cea7ad5-caeb-48de-b510-418489fa67a1)

```
plot2 = @chain plot begin
    geom_line(@aes(x = WT, y = MPG))
end
```
![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/ac9071a9-e95a-4d74-b1c3-3d257cbf5a8d)

or:
```
plot = ggplot(mtcars) + geom_point(@aes(x = WT, y = MPG))
```
```
plot2 = plot + geom_line(@aes(x = WT, y = MPG))
```
For the same results!

**Comment by rdboyes** [comment] 2024-02-28 12:55
With 0.6.0 giving a lot more control of the internals, we can now do: 

```
@chain cars begin
           @count(manufacturer)
           @arrange(n)
           ggplot(fct_inorder = true, xticklabelrotation = .5)
               geom_col(@aes(y = n, x = manufacturer))
       end
```

![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/f9739140-78fb-4d2b-b4f0-d0e535ef1b95)

**Closed** 2024-02-28 12:57 UTC

**Comment by jhelvy** [comment] 2024-02-28 13:05
I love how you are not just replicating ggplot for Julia, but actually making it better! Congrats keep it up! 💪

**Comment by kdpsingh** [comment] 2024-02-28 14:38
@rdboyes This looks amazing! Really great work.

Quick question - can we change this to `cat_inorder = true` instead of `fct_inorder = true`. Since Julia implements CategoricalArrays rather than factors, I've tried to make all the Tidier functions/args related to categoricals prefixed with `cat_*` rather than `fct_*`.

**Comment by rdboyes** [comment] 2024-02-28 14:56
Changed it in https://github.com/TidierOrg/TidierPlots.jl/commit/c04f8d346a9575f8169aeb36f3f843dc64651592 @kdpsingh! And thanks @jhelvy - let me know if there are other `ggplot` frustrations you can think of, I need to collect some examples for a "why should an R user care about this" page
